/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const InventoryEntry = IDL.Record({
  'qty' : IDL.Nat,
  'expiryDate' : IDL.Opt(Time),
  'unitId' : IDL.Nat,
  'minStock' : IDL.Nat,
  'supplierId' : IDL.Nat,
});
export const ProductUnit = IDL.Record({
  'id' : IDL.Nat,
  'stockQty' : IDL.Nat,
  'expiryDate' : IDL.Opt(Time),
  'createdAt' : Time,
  'productId' : IDL.Nat,
  'minStock' : IDL.Nat,
  'price' : IDL.Nat,
  'costPrice' : IDL.Nat,
  'unitName' : IDL.Text,
});
export const Supplier = IDL.Record({
  'id' : IDL.Nat,
  'contact' : IDL.Text,
  'name' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userType' : IDL.Variant({ 'customer' : IDL.Null, 'staff' : IDL.Null }),
  'accountId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
});
export const CustomerAccount = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'mobile' : IDL.Text,
});
export const StaffRole = IDL.Variant({
  'manager' : IDL.Null,
  'deliveryBoy' : IDL.Null,
  'cashier' : IDL.Null,
});
export const StaffAccount = IDL.Record({
  'id' : IDL.Nat,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'role' : StaffRole,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInventoryEntry' : IDL.Func([InventoryEntry], [], []),
  'addProductUnit' : IDL.Func([ProductUnit], [], []),
  'addSupplier' : IDL.Func([Supplier], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerAccounts' : IDL.Func([], [IDL.Vec(CustomerAccount)], ['query']),
  'getInventory' : IDL.Func([], [IDL.Vec(InventoryEntry)], ['query']),
  'getMyCustomerAccount' : IDL.Func([], [IDL.Opt(CustomerAccount)], ['query']),
  'getProductUnits' : IDL.Func([], [IDL.Vec(ProductUnit)], ['query']),
  'getStaffAccounts' : IDL.Func([], [IDL.Vec(StaffAccount)], ['query']),
  'getSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerCustomer' : IDL.Func([CustomerAccount], [], []),
  'registerStaff' : IDL.Func([StaffAccount, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const InventoryEntry = IDL.Record({
    'qty' : IDL.Nat,
    'expiryDate' : IDL.Opt(Time),
    'unitId' : IDL.Nat,
    'minStock' : IDL.Nat,
    'supplierId' : IDL.Nat,
  });
  const ProductUnit = IDL.Record({
    'id' : IDL.Nat,
    'stockQty' : IDL.Nat,
    'expiryDate' : IDL.Opt(Time),
    'createdAt' : Time,
    'productId' : IDL.Nat,
    'minStock' : IDL.Nat,
    'price' : IDL.Nat,
    'costPrice' : IDL.Nat,
    'unitName' : IDL.Text,
  });
  const Supplier = IDL.Record({
    'id' : IDL.Nat,
    'contact' : IDL.Text,
    'name' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'userType' : IDL.Variant({ 'customer' : IDL.Null, 'staff' : IDL.Null }),
    'accountId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
  });
  const CustomerAccount = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'mobile' : IDL.Text,
  });
  const StaffRole = IDL.Variant({
    'manager' : IDL.Null,
    'deliveryBoy' : IDL.Null,
    'cashier' : IDL.Null,
  });
  const StaffAccount = IDL.Record({
    'id' : IDL.Nat,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'role' : StaffRole,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInventoryEntry' : IDL.Func([InventoryEntry], [], []),
    'addProductUnit' : IDL.Func([ProductUnit], [], []),
    'addSupplier' : IDL.Func([Supplier], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerAccounts' : IDL.Func([], [IDL.Vec(CustomerAccount)], ['query']),
    'getInventory' : IDL.Func([], [IDL.Vec(InventoryEntry)], ['query']),
    'getMyCustomerAccount' : IDL.Func(
        [],
        [IDL.Opt(CustomerAccount)],
        ['query'],
      ),
    'getProductUnits' : IDL.Func([], [IDL.Vec(ProductUnit)], ['query']),
    'getStaffAccounts' : IDL.Func([], [IDL.Vec(StaffAccount)], ['query']),
    'getSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerCustomer' : IDL.Func([CustomerAccount], [], []),
    'registerStaff' : IDL.Func([StaffAccount, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };