/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerAccount {
  'id' : bigint,
  'name' : string,
  'email' : [] | [string],
  'mobile' : string,
}
export interface InventoryEntry {
  'qty' : bigint,
  'expiryDate' : [] | [Time],
  'unitId' : bigint,
  'minStock' : bigint,
  'supplierId' : bigint,
}
export interface ProductUnit {
  'id' : bigint,
  'stockQty' : bigint,
  'expiryDate' : [] | [Time],
  'createdAt' : Time,
  'productId' : bigint,
  'minStock' : bigint,
  'price' : bigint,
  'costPrice' : bigint,
  'unitName' : string,
}
export interface StaffAccount {
  'id' : bigint,
  'contact' : string,
  'name' : string,
  'role' : StaffRole,
}
export type StaffRole = { 'manager' : null } |
  { 'deliveryBoy' : null } |
  { 'cashier' : null };
export interface Supplier { 'id' : bigint, 'contact' : string, 'name' : string }
export type Time = bigint;
export interface UserProfile {
  'userType' : { 'customer' : null } |
    { 'staff' : null },
  'accountId' : [] | [bigint],
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInventoryEntry' : ActorMethod<[InventoryEntry], undefined>,
  'addProductUnit' : ActorMethod<[ProductUnit], undefined>,
  'addSupplier' : ActorMethod<[Supplier], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerAccounts' : ActorMethod<[], Array<CustomerAccount>>,
  'getInventory' : ActorMethod<[], Array<InventoryEntry>>,
  'getMyCustomerAccount' : ActorMethod<[], [] | [CustomerAccount]>,
  'getProductUnits' : ActorMethod<[], Array<ProductUnit>>,
  'getStaffAccounts' : ActorMethod<[], Array<StaffAccount>>,
  'getSuppliers' : ActorMethod<[], Array<Supplier>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerCustomer' : ActorMethod<[CustomerAccount], undefined>,
  'registerStaff' : ActorMethod<[StaffAccount, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];