/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProductUnit {
    id: bigint;
    stockQty: bigint;
    expiryDate?: Time;
    createdAt: Time;
    productId: bigint;
    minStock: bigint;
    price: bigint;
    costPrice: bigint;
    unitName: string;
}
export interface InventoryEntry {
    qty: bigint;
    expiryDate?: Time;
    unitId: bigint;
    minStock: bigint;
    supplierId: bigint;
}
export type Time = bigint;
export interface CustomerAccount {
    id: bigint;
    name: string;
    email?: string;
    mobile: string;
}
export interface Supplier {
    id: bigint;
    contact: string;
    name: string;
}
export interface StaffAccount {
    id: bigint;
    contact: string;
    name: string;
    role: StaffRole;
}
export interface UserProfile {
    userType: Variant_customer_staff;
    accountId?: bigint;
    name: string;
}
export enum StaffRole {
    manager = "manager",
    deliveryBoy = "deliveryBoy",
    cashier = "cashier"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_customer_staff {
    customer = "customer",
    staff = "staff"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addInventoryEntry(entry: InventoryEntry): Promise<void>;
    addProductUnit(productUnit: ProductUnit): Promise<void>;
    addSupplier(supplier: Supplier): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomerAccounts(): Promise<Array<CustomerAccount>>;
    getInventory(): Promise<Array<InventoryEntry>>;
    getMyCustomerAccount(): Promise<CustomerAccount | null>;
    getProductUnits(): Promise<Array<ProductUnit>>;
    getStaffAccounts(): Promise<Array<StaffAccount>>;
    getSuppliers(): Promise<Array<Supplier>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerCustomer(customer: CustomerAccount): Promise<void>;
    registerStaff(staff: StaffAccount, principal: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { CustomerAccount as _CustomerAccount, InventoryEntry as _InventoryEntry, ProductUnit as _ProductUnit, StaffAccount as _StaffAccount, StaffRole as _StaffRole, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addInventoryEntry(arg0: InventoryEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventoryEntry(to_candid_InventoryEntry_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventoryEntry(to_candid_InventoryEntry_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addProductUnit(arg0: ProductUnit): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProductUnit(to_candid_ProductUnit_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProductUnit(to_candid_ProductUnit_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSupplier(arg0: Supplier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSupplier(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSupplier(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerAccounts(): Promise<Array<CustomerAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerAccounts();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerAccounts();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventory(): Promise<Array<InventoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventory();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventory();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCustomerAccount(): Promise<CustomerAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCustomerAccount();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCustomerAccount();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductUnits(): Promise<Array<ProductUnit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductUnits();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductUnits();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaffAccounts(): Promise<Array<StaffAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffAccounts();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffAccounts();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSuppliers(): Promise<Array<Supplier>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuppliers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuppliers();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerCustomer(arg0: CustomerAccount): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCustomer(to_candid_CustomerAccount_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCustomer(to_candid_CustomerAccount_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async registerStaff(arg0: StaffAccount, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStaff(to_candid_StaffAccount_n33(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStaff(to_candid_StaffAccount_n33(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_CustomerAccount_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerAccount): CustomerAccount {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryEntry_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryEntry): InventoryEntry {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ProductUnit_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductUnit): ProductUnit {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_StaffAccount_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffAccount): StaffAccount {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_StaffRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffRole): StaffRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerAccount]): CustomerAccount | null {
    return value.length === 0 ? null : from_candid_CustomerAccount_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    email: [] | [string];
    mobile: string;
}): {
    id: bigint;
    name: string;
    email?: string;
    mobile: string;
} {
    return {
        id: value.id,
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.email)),
        mobile: value.mobile
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    qty: bigint;
    expiryDate: [] | [_Time];
    unitId: bigint;
    minStock: bigint;
    supplierId: bigint;
}): {
    qty: bigint;
    expiryDate?: Time;
    unitId: bigint;
    minStock: bigint;
    supplierId: bigint;
} {
    return {
        qty: value.qty,
        expiryDate: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.expiryDate)),
        unitId: value.unitId,
        minStock: value.minStock,
        supplierId: value.supplierId
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    stockQty: bigint;
    expiryDate: [] | [_Time];
    createdAt: _Time;
    productId: bigint;
    minStock: bigint;
    price: bigint;
    costPrice: bigint;
    unitName: string;
}): {
    id: bigint;
    stockQty: bigint;
    expiryDate?: Time;
    createdAt: Time;
    productId: bigint;
    minStock: bigint;
    price: bigint;
    costPrice: bigint;
    unitName: string;
} {
    return {
        id: value.id,
        stockQty: value.stockQty,
        expiryDate: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.expiryDate)),
        createdAt: value.createdAt,
        productId: value.productId,
        minStock: value.minStock,
        price: value.price,
        costPrice: value.costPrice,
        unitName: value.unitName
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    contact: string;
    name: string;
    role: _StaffRole;
}): {
    id: bigint;
    contact: string;
    name: string;
    role: StaffRole;
} {
    return {
        id: value.id,
        contact: value.contact,
        name: value.name,
        role: from_candid_StaffRole_n29(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: {
        customer: null;
    } | {
        staff: null;
    };
    accountId: [] | [bigint];
    name: string;
}): {
    userType: Variant_customer_staff;
    accountId?: bigint;
    name: string;
} {
    return {
        userType: from_candid_variant_n10(_uploadFile, _downloadFile, value.userType),
        accountId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.accountId)),
        name: value.name
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: null;
} | {
    staff: null;
}): Variant_customer_staff {
    return "customer" in value ? Variant_customer_staff.customer : "staff" in value ? Variant_customer_staff.staff : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: null;
} | {
    deliveryBoy: null;
} | {
    cashier: null;
}): StaffRole {
    return "manager" in value ? StaffRole.manager : "deliveryBoy" in value ? StaffRole.deliveryBoy : "cashier" in value ? StaffRole.cashier : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomerAccount>): Array<CustomerAccount> {
    return value.map((x)=>from_candid_CustomerAccount_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryEntry>): Array<InventoryEntry> {
    return value.map((x)=>from_candid_InventoryEntry_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductUnit>): Array<ProductUnit> {
    return value.map((x)=>from_candid_ProductUnit_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StaffAccount>): Array<StaffAccount> {
    return value.map((x)=>from_candid_StaffAccount_n27(_uploadFile, _downloadFile, x));
}
function to_candid_CustomerAccount_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerAccount): _CustomerAccount {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_InventoryEntry_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventoryEntry): _InventoryEntry {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ProductUnit_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductUnit): _ProductUnit {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_StaffAccount_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffAccount): _StaffAccount {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_StaffRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffRole): _StaffRole {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    qty: bigint;
    expiryDate?: Time;
    unitId: bigint;
    minStock: bigint;
    supplierId: bigint;
}): {
    qty: bigint;
    expiryDate: [] | [_Time];
    unitId: bigint;
    minStock: bigint;
    supplierId: bigint;
} {
    return {
        qty: value.qty,
        expiryDate: value.expiryDate ? candid_some(value.expiryDate) : candid_none(),
        unitId: value.unitId,
        minStock: value.minStock,
        supplierId: value.supplierId
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    email?: string;
    mobile: string;
}): {
    id: bigint;
    name: string;
    email: [] | [string];
    mobile: string;
} {
    return {
        id: value.id,
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        mobile: value.mobile
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    contact: string;
    name: string;
    role: StaffRole;
}): {
    id: bigint;
    contact: string;
    name: string;
    role: _StaffRole;
} {
    return {
        id: value.id,
        contact: value.contact,
        name: value.name,
        role: to_candid_StaffRole_n35(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: Variant_customer_staff;
    accountId?: bigint;
    name: string;
}): {
    userType: {
        customer: null;
    } | {
        staff: null;
    };
    accountId: [] | [bigint];
    name: string;
} {
    return {
        userType: to_candid_variant_n39(_uploadFile, _downloadFile, value.userType),
        accountId: value.accountId ? candid_some(value.accountId) : candid_none(),
        name: value.name
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    stockQty: bigint;
    expiryDate?: Time;
    createdAt: Time;
    productId: bigint;
    minStock: bigint;
    price: bigint;
    costPrice: bigint;
    unitName: string;
}): {
    id: bigint;
    stockQty: bigint;
    expiryDate: [] | [_Time];
    createdAt: _Time;
    productId: bigint;
    minStock: bigint;
    price: bigint;
    costPrice: bigint;
    unitName: string;
} {
    return {
        id: value.id,
        stockQty: value.stockQty,
        expiryDate: value.expiryDate ? candid_some(value.expiryDate) : candid_none(),
        createdAt: value.createdAt,
        productId: value.productId,
        minStock: value.minStock,
        price: value.price,
        costPrice: value.costPrice,
        unitName: value.unitName
    };
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffRole): {
    manager: null;
} | {
    deliveryBoy: null;
} | {
    cashier: null;
} {
    return value == StaffRole.manager ? {
        manager: null
    } : value == StaffRole.deliveryBoy ? {
        deliveryBoy: null
    } : value == StaffRole.cashier ? {
        cashier: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_customer_staff): {
    customer: null;
} | {
    staff: null;
} {
    return value == Variant_customer_staff.customer ? {
        customer: null
    } : value == Variant_customer_staff.staff ? {
        staff: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
